server:
  port: 8000
  servlet:
    context-path: /
# port&context-path설정 / server.xml에 적던 것 (tomcat)
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
# JSP 설정 ViewResolver 설정
# request 요청이 오면 응답을 할 때 데이터를 응답할지 / 파일을 응답할지 정하는 것

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/opggpro3?serverTimezone=Asia/Seoul
    username: opgg3
    password: 1029
# database connect / jsp에서 context.xml에 적던 것
    
  jpa:
    hibernate:
      ddl-auto: update # 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
# 
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 509235013631-rgjilk5tg8pqe1etad3omoieqvnmarli.apps.googleusercontent.com
            client-secret: -upUc9J9raJoIo3mzCA85Jq3
            scope:
            - email
            - profile